feat: [BACKEND] Description and cover has no translations in search results
fagbokforlaget/erudio-client pull request #12
Opened 2023-01-10 10:15 UTC by Stadnicki

2023-01-10 10:47 UTC, iapain approved these changes
LGTM 👍🏼

2023-01-10 17:18 UTC, matuz approved these changes

2023-01-11 11:03 UTC, espresse requested changes

2023-01-11 11:03 UTC, espresse commented on src/localization/dto/localization-dto.ts
> +  readonly object_id: string;
@Stadnicki do you really get `object_id` and not `objectId` property in localization objects? All properties should be camelCase in our services responses.

2023-01-11 11:25 UTC, Stadnicki commented on src/localization/dto/localization-dto.ts
> +  readonly object_id: string;
You're right, I've missed that LocalizationOutputDto from edtech-localization-service is not eventual response shape as class-transformer is used.

2023-01-11 11:31 UTC, espresse approved these changes

2023-01-11 23:59 UTC, merged